import type { Metadata } from "next";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that provides the HTML structure, global font, and top-level providers for the application.
 *
 * This component renders an <html> element with lang="en" and a <body> that applies the DM Sans font and antialiasing.
 * It wraps the app content with NuqsAdapter and TRPCReactProvider and includes the Toaster for global notifications.
 *
 * @param children - The page or application content to render inside the layout's providers
 * @returns The root HTML element containing the body with global providers and the rendered children
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <NuqsAdapter>

          <TRPCReactProvider>
            {children}
            <Toaster />
          </TRPCReactProvider>
        </NuqsAdapter>

      </body>
    </html>
  );
}